// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAEtaaFdU3h8r6qaF1Gs4iLiW48w5jT0M',
    appId: '1:168771327351:web:fb877692bce254c1e43d72',
    messagingSenderId: '168771327351',
    projectId: 'dohwi-player',
    authDomain: 'dohwi-player.firebaseapp.com',
    storageBucket: 'dohwi-player.firebasestorage.app',
    measurementId: 'G-FBWHQ8QPD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_NL_ZMjTnlRm5X3VE4pWQ92gQe7wdU8',
    appId: '1:168771327351:android:ee5b8ab48f8b9b2de43d72',
    messagingSenderId: '168771327351',
    projectId: 'dohwi-player',
    storageBucket: 'dohwi-player.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuDgIBYGHyu1PkbYdo3JdG8Z2oeHXUGBw',
    appId: '1:168771327351:ios:ac734062f5e9eab6e43d72',
    messagingSenderId: '168771327351',
    projectId: 'dohwi-player',
    storageBucket: 'dohwi-player.firebasestorage.app',
    iosBundleId: 'com.example.kidsMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuDgIBYGHyu1PkbYdo3JdG8Z2oeHXUGBw',
    appId: '1:168771327351:ios:ac734062f5e9eab6e43d72',
    messagingSenderId: '168771327351',
    projectId: 'dohwi-player',
    storageBucket: 'dohwi-player.firebasestorage.app',
    iosBundleId: 'com.example.kidsMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAEtaaFdU3h8r6qaF1Gs4iLiW48w5jT0M',
    appId: '1:168771327351:web:ac154e6d6d33d0c6e43d72',
    messagingSenderId: '168771327351',
    projectId: 'dohwi-player',
    authDomain: 'dohwi-player.firebaseapp.com',
    storageBucket: 'dohwi-player.firebasestorage.app',
    measurementId: 'G-3CJ31QZWV8',
  );
}
